# Generated by Django 2.2.7 on 2019-11-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wcount',
            old_name='title',
            new_name='header',
        ),
    ]
